//
//  SecureKeyStore.swift
//  ScreenGrabber
//
//  Provides secure storage for internal API keys embedded in the app bundle.
//  Uses XOR-based byte obfuscation for basic protection against static analysis.
//
//  NOTE: For production hardening, replace the XOR scheme with CryptoKit AES-GCM
//  and store the symmetric key in the app's Keychain (not in source).
//
//  HOW TO UPDATE INTERNAL KEYS — see API_MAINTENANCE.md for full instructions.
//  Quick reference:
//    1. In a debug build, call: SecureKeyStore.obfuscate(key: "YOUR_API_KEY")
//    2. Print the resulting [UInt8] array
//    3. Replace `obfuscatedInternalKey` below with the new array
//    4. Commit only the obfuscated bytes — never the plaintext key
//

import Foundation

enum SecureKeyStore {

    // MARK: - Configuration

    /// XOR-obfuscated internal API key bytes.
    /// Replace with your generated bytes (see above / API_MAINTENANCE.md).
    /// Empty array means "no internal key configured" → BYOK only.
    private static let obfuscatedInternalKey: [UInt8] = []

    /// Salt for XOR obfuscation. Change this when rotating the key.
    private static let salt: [UInt8] = [
        0x53, 0x47, 0x33, 0x2E, 0x30, 0x49, 0x4E, 0x54  // "SG3.0INT"
    ]

    // MARK: - Public Interface

    /// Decrypts and returns the embedded internal API key.
    /// Returns nil if no key is configured or if the decrypted string is empty.
    static var internalAPIKey: String? {
        #if DEBUG
        // In debug builds, prefer .env over embedded key
        if let envKey = ProcessInfo.processInfo.environment["SG_INTERNAL_KEY"], !envKey.isEmpty {
            return envKey
        }
        #endif
        guard !obfuscatedInternalKey.isEmpty else { return nil }
        let bytes = deobfuscate(obfuscatedInternalKey, salt: salt)
        let key = String(bytes: bytes, encoding: .utf8)
        return key?.isEmpty == false ? key : nil
    }

    /// Returns the AI backend endpoint URL.
    /// Prefers the SG_AI_ENDPOINT environment variable in DEBUG builds;
    /// falls back to the hardcoded production URL in Release.
    static var aiEndpointURL: URL? {
        #if DEBUG
        if let raw = ProcessInfo.processInfo.environment["SG_AI_ENDPOINT"], !raw.isEmpty {
            return URL(string: raw)
        }
        #endif
        // TODO: Replace with your production endpoint before shipping
        // return URL(string: "https://api.yourserver.com/ai")
        return nil
    }

    // MARK: - Obfuscation Helpers

    private static func deobfuscate(_ bytes: [UInt8], salt: [UInt8]) -> [UInt8] {
        guard !salt.isEmpty else { return bytes }
        return bytes.enumerated().map { idx, byte in byte ^ salt[idx % salt.count] }
    }

    /// Obfuscates a plaintext key for embedding.
    /// Use this in a one-off debug build to generate the bytes for `obfuscatedInternalKey`.
    /// NEVER call this at runtime in production.
    static func obfuscate(key: String) -> [UInt8] {
        let bytes = Array(key.utf8)
        return bytes.enumerated().map { idx, byte in byte ^ salt[idx % salt.count] }
    }
}
